AplicacaoWeb/Models/Model/Empresa.cs
using AplicacaoWeb.Uteis;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace AplicacaoWeb.Models.Model
{
    public class Empresa
    {
        public int IdEmpresa { get; set; }
        public string RazaoSocial { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public string IM { get; set; }
        public int Numero { get; set; }
        public string Complemento { get; set; }

        public List<Empresa> ListarTodasEmpresas()
        {
            List<Empresa> lista = new List<Empresa>();
            Empresa item;
            DAL objDAL = new DAL();
            string sql = "SELECT idEmpresa, RazaoSocial, CNPJ, IE, IM, Complemento FROM Empresa order by RazaoSocial asc";
            DataTable dt = objDAL.RetDataTable(sql);

            for (int i = 0; i < dt.Rows.Count; i++)
            {
                item = new Empresa
                {
                    IdEmpresa = (int)dt.Rows[i]["IdEmpresa"],
                    RazaoSocial = dt.Rows[i]["RazaoSocial"].ToString(),
                    CNPJ = dt.Rows[i]["CNPJ"].ToString(),
                    IE = dt.Rows[i]["IE"].ToString(),
                    IM = dt.Rows[i]["IM"].ToString(),
                    Complemento = dt.Rows[i]["Complemento"].ToString()
                };
                lista.Add(item);
            }
            return lista;
        }
        public Empresa RetornarEmpresa(int? id)
        {

            Empresa item;
            DAL objDAL = new DAL();
            string sql = $"SELECT idEmpresa, RazaoSocial, CNPJ, IE, IM, Complemento FROM Empresa where idEmpresa ='{id}' order by RazaoSocial asc";
            DataTable dt = objDAL.RetDataTable(sql);

            item = new Empresa
            {
                IdEmpresa = (int)dt.Rows[0]["IdEmpresa"],
                RazaoSocial = dt.Rows[0]["RazaoSocial"].ToString(),
                CNPJ = dt.Rows[0]["CNPJ"].ToString(),
                IE = dt.Rows[0]["IE"].ToString(),
                IM = dt.Rows[0]["IM"].ToString(),
                Complemento = dt.Rows[0]["Complemento"].ToString()
            };

            return item;
        }
        public void Gravar()
        {
            DAL objDal = new DAL();
            string sql = string.Empty;

            if (IdEmpresa == 0)
            {
                sql = $"UPDATE EMPRESA SET RAZAOSOCIAL='{RazaoSocial}', CNPJ='{CNPJ}', IE='{IE}', IM='{IM}', COMPLEMENTO='{Complemento}' WHERE IDEMPRESA = '{IdEmpresa}'";
            }
            else
            {
                sql = $"INSERT INTO EMPRESA(RazaoSocial, CNPJ, IE, IM, COMPLEMENTO) VALUES('{RazaoSocial}', '{CNPJ}', '{IE}', '{IM}', '{Complemento}')";
            }

            objDal.ExecutarComandoSQL(sql);
        }

        //DELETE
        public void Excluir(int id)
        {
            DAL objDal = new DAL();
            string sql = $"DELETE FROM EMPRESA WHERE IDEMPRESA='{id}'";
            objDal.ExecutarComandoSQL(sql);
        }


    }
}

AplicacaoWeb/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AplicacaoWeb.Models.Model;


namespace AplicacaoWeb.Controllers
{
    public class EmpresasController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.ListaEmpresas = new Empresa().ListarTodasEmpresas();
            return View();
        }
        public IActionResult Cadastro(int? id)
        {
            if (id != null)
            {
                //Carregar o registro do cliente numa viewBag
                ViewBag.Empresa = new Empresa().RetornarEmpresa(id);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                empresa.Gravar();
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Excluir(int id)
        {
            ViewData["IdExcluir"] = id;
            return View();
        }

        public IActionResult ExcluirEmpresa(int id)
        {
            new Empresa().Excluir(id);
            return View();
        }
    }
}
    

AplicacaoWeb/Views/Empresas/Cadastro.cshtml
@model AplicacaoWeb.Models.Model.Empresa
<h2>Cadastro de Empresass</h2>

<br />

<form asp-controller="Empresas" asp-action="Cadastro">
    <input type="hidden" asp-for="IdEmpresa" value="@try { @ViewBag.Empresa.IdEmpresa } catch { }" />

    <div class="form-group">
        <label>Nome da Empresa</label>
        <input asp-for="RazaoSocial" type="text" class="form-control" value="@try { @ViewBag.Empresa.RazaoSocial } catch { }" />
        <span asp-validation-for="RazaoSocial" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>CNPJ</label>
        <input asp-for="CNPJ" type="text" class="form-control" value="@try { @ViewBag.Empresa.CNPJ } catch { }" />
        <span asp-validation-for="CNPJ" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Incriçao Estadual</label>
        <input asp-for="IE" type="text" class="form-control" value="@try { @ViewBag.Empresa.IE } catch { }" />
        <span asp-validation-for="IE" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Incriçao Municipal</label>
        <input asp-for="IM" type="text" class="form-control" value="@try { @ViewBag.Empresa.IM } catch { }" />
        <span asp-validation-for="IM" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Complemento</label>
        <input asp-for="Complemento" type="text" class="form-control" value="@try { @ViewBag.Empresa.Complemento } catch { }" />
        <span asp-validation-for="Complemento" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

AplicacaoWeb/Views/Empresas/Excluir.cshtml
<h2>Excluir Empresa</h2>

<h3>Deseja realmente excluir a empresa selecionado ?</h3>

<button type="button" class="btn btn-danger" onclick="Nao()">Não</button>
<button type="button" class="btn btn-success" onclick="Sim()">Sim</button>

<script>
    function Sim()
    {
        window.location.href = '../../Empresas/ExcluirEmpresa/' + '@ViewData["IdExcluir"].ToString()';
    }

    function Nao() {
        window.location.href = '../../Empresas/Index'
    }
</script>

AplicacaoWeb/Views/Empresas/ExcluirEmpresa.cshtml
<h2>Empresa Excluida com Sucesso!</h2>

<button type="button" class="btn btn-primary" onclick="Voltar()">Listagem de Empresa</button>

<script>

    function Voltar() {
        window.location.href = '../../Empresas/Index';
    }
</script>

AplicacaoWeb/Views/Empresas/Index.cshtml
<h3>Lista de Empresas</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>Codigo</th>
            <th>Nome</th>
            <th>CNPJ</th>
            <th>Inscriçao Estadual</th>
            <th>Inscrição Municipal</th>
            <th>Complemento</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in (List<AplicacaoWeb.Models.Model.Empresa>)ViewBag.ListaEmpresas)
            {
                <tr>
                    <td><button type="button" class="btn btn-warning" onclick="Editar(@item.IdEmpresa)">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.IdEmpresa)">Excluir</button></td>

                    <td>@item.IdEmpresa</td>
                    <td>@item.RazaoSocial</td>
                    <td>@item.CNPJ</td>
                    <td>@item.IE</td>
                    <td>@item.IM</td>
                    <td>@item.Complemento</td>

                </tr>
            }
        }
    </tbody>
</table>
<br />
<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Cadastrar Empresa</button>

<script>
    function Cadastrar()
    {
        window.location.href = "../Empresas/Cadastro"
    }

    function Editar(id) {
        window.location.href = "../Empresas/Cadastro/" + id;
    }

    function Excluir(IdEmpresa) {
        window.location.href = "../Empresas/Excluir/" + IdEmpresa;
    }

</script>