AplicacaoWeb/Models/Model/Curso.cs
using AplicacaoWeb.Uteis;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacaoWeb.Models.Model
{
    public class Curso
    {
        public string IdCurso { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
        public string IdInstituicao { get; set; }


        public List<Instituicao> RetornarListaInstituicoes(int? id)
        {
            return new Instituicao().ListarTodasInstituicoes();
        }


        public List<Curso> ListarTodosCursos()
        {
            List<Curso> lista = new List<Curso>();
            Curso item;
            DAL objDAL = new DAL();
            string sql = "SELECT C.IdCurso, C.Nome, C.Tipo, IT.IdInstituicao from Curso C join Instituicao IT on C.IdInstituicao = IT.IdInstituicao order by C.Nome asc";
            DataTable dt = objDAL.RetDataTable(sql);

            for (int i = 0; i < dt.Rows.Count; i++)
            {
                item = new Curso
                {
                    IdCurso = dt.Rows[i]["IDCURSO"].ToString(),
                    Nome = dt.Rows[i]["NOME"].ToString(),
                    Tipo = dt.Rows[i]["TIPO"].ToString(),
                    IdInstituicao = dt.Rows[i]["IDINSTITUICAO"].ToString(),

                };
                lista.Add(item);
            }
            return lista;
        }

        public Curso RetornarCurso(int? id)
        {

            Curso item;
            DAL objDAL = new DAL();
            string sql = $"SELECT idCurso, Nome, Tipo, IdInstituicao from Curso ";
            DataTable dt = objDAL.RetDataTable(sql);

            item = new Curso
            {
                IdCurso = dt.Rows[0]["IDCURSO"].ToString(),
                Nome = dt.Rows[0]["NOME"].ToString(),
                Tipo = dt.Rows[0]["TIPO"].ToString(),
                IdInstituicao = dt.Rows[0]["IDINSTITUICAO"].ToString(),

            };

            return item;
        }

        public void Gravar()
        {
            DAL objDal = new DAL();
            string sql = string.Empty;

            if (IdCurso != null)
            {
                sql = $"UPDATE Curso SET NOME='{Nome}', TIPO='{Tipo}', IDINSTITUICAO='{IdInstituicao}' WHERE IDCURSO = '{IdCurso}'";
            }
            else
            {
                sql = $"INSERT INTO Curso(Nome, Tipo, idInstituicao) VALUES('{Nome}', '{Tipo}', '{IdInstituicao}')";
            }

            objDal.ExecutarComandoSQL(sql);
        }

        //DELETE
        public void Excluir(int id)
        {
            DAL objDal = new DAL();
            string sql = $"DELETE FROM Curso WHERE IDCURSO='{id}'";
            objDal.ExecutarComandoSQL(sql);
        }
    }
}

AplicacaoWeb/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplicacaoWeb.Models.Model;
using Microsoft.AspNetCore.Mvc;

namespace AplicacaoWeb.Controllers
{
    public class CursoController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.ListarCursos = new Curso().ListarTodosCursos();
            return View();
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            if (id != null)
            {
                //Carregar o registro do curso numa viewBag
                ViewBag.Curso = new Curso().RetornarCurso(id);
            }
            else
            {
                ViewBag.ListarIntituicoes = new Curso().RetornarListaInstituicoes(id);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(Curso curso)
        {
            if (ModelState.IsValid)
            {
                curso.Gravar();
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Excluir(int id)
        {
            ViewData["IdExcluir"] = id;
            return View();
        }

        public IActionResult ExcluirCurso(int id)
        {
            new Curso().Excluir(id);
            return View();
        }
    }
}

AplicacaoWeb/Views/Curso/Cadastro.cshtml
@model AplicacaoWeb.Models.Model.Curso

<h2>Cadastro de Cursos</h2>

<br />

<form asp-controller="Curso" asp-action="Cadastro">
    <input type="hidden" asp-for="IdCurso" value="@try { @ViewBag.Curso.IdCurso } catch { }" />

    <div class="form-group">
        <label>Nome do Curso</label>
        <input asp-for="Nome" type="text" class="form-control" value="@try { @ViewBag.Curso.Nome } catch { }" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Tipo</label>
        <input asp-for="Tipo" type="text" class="form-control" value="@try { @ViewBag.Curso.Tipo } catch { }" />
        <span asp-validation-for="Tipo" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Empresa</label>
        <select asp-for="IdInstituicao" class="form-control">
            @{
                foreach (var item in (List<AplicacaoWeb.Models.Model.Instituicao>)ViewBag.ListarIntituicoes)
                {
                    <option value="@item.IdInstituicao">@item.Nome</option>
                }
            }
        </select>
    </div>
    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

AplicacaoWeb/Views/Curso/Excluir.cshtml
<h2>Excluir Curso</h2>

<h3>Deseja realmente excluir oCurso selecionado ?</h3>

<button type="button" class="btn btn-danger" onclick="Nao()">Não</button>
<button type="button" class="btn btn-success" onclick="Sim()">Sim</button>

<script>
    function Sim()
    {
        window.location.href = '../../Curso/ExcluirCurso/' + '@ViewData["IdExcluir"].ToString()';
    }

    function Nao() {
        window.location.href = '../../Curso/Index'
    }
</script>

AplicacaoWeb/Views/Curso/ExcluirCurso.cshtml
<h2>Curso Excluido com Sucesso!</h2>

<button type="button" class="btn btn-primary" onclick="Voltar()">Listagem de Cursos</button>

<script>

    function Voltar() {
        window.location.href = '../../Curso/Index';
    }
</script>

AplicacaoWeb/Views/Curso/Index.cshtml
<h3>Lista de Cursos</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>Codigo</th>
            <th>Nome</th>
            <th>Tipo</th>
            <th>ID Instituição</th>

        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in (List<AplicacaoWeb.Models.Model.Curso>)ViewBag.ListarCursos)
            {
                <tr>
                    <td><button type="button" class="btn btn-warning" onclick="Editar(@item.IdCurso)">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.IdCurso)">Excluir</button></td>

                    <td>@item.IdCurso</td>
                    <td>@item.Nome</td>
                    <td>@item.Tipo</td>
                    <td>@item.IdInstituicao</td>

                </tr>
            }
        }
    </tbody>
</table>
<br />
<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Cadastrar Curso</button>

<script>
    function Cadastrar() {
        window.location.href = "../Curso/Cadastro"
    }

    function Editar(id) {
        window.location.href = "../Curso/Cadastro/" + id;
    }

    function Excluir(Id) {
        window.location.href = "../Curso/Excluir/" + Id;
    }

</script>