AplicacaoWeb/Models/Model/Instituicao.cs
using AplicacaoWeb.Uteis;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace AplicacaoWeb.Models.Model
{
    public class Instituicao
    {
        public string IdInstituicao { get; set; }
        public string Nome { get; set; }
        public string RegistroDiario { get; set; }
        public int IdEmpresa { get; set; }

        public ICollection<Empresa> Empresas { get; set; } = new List<Empresa>();

        public List<Empresa> RetornarListaEmpresas(int? id)
        {
            return new Empresa().ListarTodasEmpresas();
        }


        public List<Instituicao> ListarTodasInstituicoes()
        {
            List<Instituicao> lista = new List<Instituicao>();
            Instituicao item;
            DAL objDAL = new DAL();
            string sql = "SELECT idInstituicao, Nome, RegistroDiario, IdEmpresa from Instituicao";
            DataTable dt = objDAL.RetDataTable(sql);
         
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                item = new Instituicao
                {
                    IdInstituicao = dt.Rows[i]["IDINSTITUICAO"].ToString(),
                    Nome = dt.Rows[i]["NOME"].ToString(),
                    RegistroDiario = dt.Rows[i]["REGISTRODIARIO"].ToString(),
                    IdEmpresa = (int)dt.Rows[i]["IDEMPRESA"],
               
                };
                lista.Add(item);
            }
            return lista;
        }

        public Instituicao RetornarInstituicao(int? id)
        {

            Instituicao item;
            DAL objDAL = new DAL();
            string sql = $"SELECT idInstituicao, Nome, RegistroDiario, IdEmpresa from Instituicao ";
            DataTable dt = objDAL.RetDataTable(sql);

            item = new Instituicao
            {
                IdInstituicao = dt.Rows[0]["IDINSTITUICAO"].ToString(),
                Nome = dt.Rows[0]["NOME"].ToString(),
                RegistroDiario = dt.Rows[0]["REGISTRODIARIO"].ToString(),
                IdEmpresa = (int)dt.Rows[0]["IDEMPRESA"],
               
            };

            return item;
        }
        public void Gravar()
        {
            DAL objDal = new DAL();
            string sql = string.Empty;

            if (IdInstituicao != null)
            {
                sql = $"UPDATE INSTITUICAO SET NOME='{Nome}', REGISTRODIARIO='{RegistroDiario}', IDEMPRESA='{IdEmpresa}' WHERE IDINSTITUICAO = '{IdInstituicao}'";
            }
            else
            {
                sql = $"INSERT INTO Instituicao(Nome, RegistroDiario, idEmpresa) VALUES('{Nome}', '{RegistroDiario}', '{IdEmpresa}')";
            }

            objDal.ExecutarComandoSQL(sql);
        }

        //DELETE
        public void Excluir(int id)
        {
            DAL objDal = new DAL();
            string sql = $"DELETE FROM INSTITUICAO WHERE IDINSTITUICAO='{id}'";
            objDal.ExecutarComandoSQL(sql);
        }
    }
}

AplicacaoWeb/Controllers/InstituicaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplicacaoWeb.Models.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using AplicacaoWeb.Uteis;


namespace AplicacaoWeb.Controllers
{
    public class InstituicaoController : Controller
    {
        private readonly SisEduContext _context;


        public InstituicaoController(SisEduContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.ListarInstituicoes = new Instituicao().ListarTodasInstituicoes();
            return View();
        }

        [HttpGet]
        public IActionResult Cadastro(int id)
        {
            if (id == 0)
            {
                //Carregar o registro da instituicao numa viewBag
                ViewBag.Instituicao = new Instituicao().RetornarInstituicao(id);
            }
            else 
            {
                // ViewBag.ListarEmpresas = new Instituicao().RetornarListaEmpresas(id);
                //   ViewBag.ListarEmpresas = new SelectList(new Instituicao().RetornarListaEmpresas(id));

                ViewBag.ListarEmpresas = new SelectList(_context.Instituicao, "IdEmpresa", "RazaoSocial");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(Instituicao instituicao)
        {
            if (ModelState.IsValid)
            {
                instituicao.Gravar();
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Excluir(int id)
        {
            ViewData["IdExcluir"] = id;
            return View();
        }

        public IActionResult ExcluirInstituicao(int id)
        {
            new Instituicao().Excluir(id);
            return View();
        }
    }
}

AplicacaoWeb/Views/Instituicao/Cadastro.cshtml
@model AplicacaoWeb.Models.Model.Instituicao

<h2>Cadastro de Instituições</h2>

<br />

<form asp-controller="Instituicao" asp-action="Cadastro">
    <input type="hidden" asp-for="IdInstituicao" value="@try { @ViewBag.Instituicao.IdInstituicao } catch { }" />

    <div class="form-group">
        <label>Nome da Instituição</label>
        <input asp-for="Nome" type="text" class="form-control" value="@try { @ViewBag.Instituicao.Nome } catch { }" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Registro Diario</label>
        <input asp-for="RegistroDiario" type="text" class="form-control" value="@try { @ViewBag.Instituicao.RegistroDiario } catch { }" />
        <span asp-validation-for="RegistroDiario" class="text-danger"></span>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Empresas, htmlAttributes: new { @class = "col-sm-12 col-form-label font-weight-bold" })
        <div class="col-md-10">
            @Html.DropDownList("ListarEmpresas", null, new { @class = "form-control", @style = "border-radius: 10px;" })
            @Html.ValidationMessageFor(model => model.Empresas, "", new { @class = "text-danger" })
        </div>


        @*<label>Empresa</label>
        <select  asp-for="IdEmpresa"  class="form-control">
            <option>Selecione a Empresa</option>
            @{

                foreach (var item in (List<AplicacaoWeb.Models.Model.Empresa>)ViewBag.ListarEmpresas)
                {

                    <option value="@item.IdEmpresa">@item.RazaoSocial</option>
                }
            }
        </select>*@
    </div>
    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

AplicacaoWeb/Views/Instituicao/Excluir.cshtml
<h2>Excluir Instituição</h2>

<h3>Deseja realmente excluir a instituição selecionada ?</h3>

<button type="button" class="btn btn-danger" onclick="Nao()">Não</button>
<button type="button" class="btn btn-success" onclick="Sim()">Sim</button>

<script>
    function Sim()
    {
        window.location.href = '../../Instituicao/ExcluirInstituicao/' + '@ViewData["IdExcluir"].ToString()';
    }

    function Nao() {
        window.location.href = '../../Instituicao/Index'
    }
</script>

AplicacaoWeb/Views/Instituicao/ExcluirInstituicao.cshtml
<h2>Instituição Excluida com Sucesso!</h2>

<button type="button" class="btn btn-primary" onclick="Voltar()">Listagem de Instituições</button>

<script>

    function Voltar() {
        window.location.href = '../../Instituicao/Index';
    }
</script>

AplicacaoWeb/Views/Instituicao/Index.cshtml
<h3>Lista de Instituições</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>Codigo</th>
            <th>Nome</th>
            <th>Registro Diario</th>
            <th>ID Empresa</th>

        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in (List<AplicacaoWeb.Models.Model.Instituicao>)ViewBag.ListarInstituicoes)
            {
                <tr>
                    <td><button type="button" class="btn btn-warning" onclick="Editar(@item.IdInstituicao)">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.IdInstituicao)">Excluir</button></td>

                    <td>@item.IdInstituicao</td>
                    <td>@item.Nome</td>
                    <td>@item.RegistroDiario</td>
                    <td>@item.IdEmpresa</td>

                </tr>
            }
        }
    </tbody>
</table>
<br />
<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Cadastrar Instituição</button>

<script>
    function Cadastrar()
    {
        window.location.href = "../Instituicao/Cadastro"
    }

    function Editar(id) {
        window.location.href = "../Instituicao/Cadastro/" + id;
    }

    function Excluir(IdInstituicao) {
        window.location.href = "../Instituicao/Excluir/" + IdInstituicao;
    }

</script>